version: "3"
services:
  
  frontend:
    container_name: SocketIO_Front_end
    stdin_open: true
    build:
      context: ./cliente
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./cliente:/usr/src/app
  
  backend:
    container_name: SocketIO_Back_end
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/src/app

  # mysql:
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_USER=henry
  #     - MYSQL_PASSWORD=examenhenry123
  #   ports:
  #     - 3354:3354
    

