version: "3"
services:
  
  frontend:
    container_name: SocketIO_Front_end
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
  
  backend:
    container_name: SocketIO_Back_end
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/src/app

  mysql:
    container_name: SocketIO_MySql
    image: mysql
    volumes:
      - ./api/src/services/db.js:/usr/src/app
    ports:
      - "3306:3306"
    

